### ISSUE TITLE
[tslint] Consider enabling more rules

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/sprotty#123]
When enabling the linter, I've disabled some rules in the `tslint.json`.

The most striking one is `"forin": false`. It reports an error in about 8 cases and I am not sure whether or how we should deal with that. We should have a look at that after going public.

**Comment by JanKoehnlein** [comment]
@jbicker could you have a look at the forin issue?

**Comment by spoenemann** [comment]
I've reworked the TSLint configuration in #204. The `forin` rule is now active since it seems to make sense to avoid it unless necessary, see the [MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in).
