### ISSUE TITLE
[graph] Manipulation of edge control points

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/sprotty#133]
sprotty currently supports polyline edges. In the following, we refer to the inner points of the polyline as the control points (CPs). We leave the start and endpoint to a separate issue.

CPs of edges should be editable
- [x] SControlPoint should become an SModel class
- [x] SEdge must be be selectable
- [x] on selection of an edge, its CPs should appear as circular handles
- [x] on deselection of an edge, its CPs should disappear
- [x] CPs should be selectable as well
- [x] CPs should be selectable and moveable
- [ ] It should be possible to remove control points from an edge
- [x] It should be possible to add a control point to an edge

Feel free to break this down into smaller Github issues.

**Comment by jbicker** [comment]
Proposal for actual behaviour
- Simple click on an edge brings it into edit mode, the routing points are showing up
- double click on an edge segment creates a new routing point handle
- dragging a routing point handle creates an actual routing point
- double click on a routing point removes it

Further thoughts
- right click on a routing point shows a routing point context menu where one can choose between kinds of routing point (bezier, polygon, rectangular…)
- right click on an edge segment shows a edge context menu where one can choose between kind of edge

**Comment by JanKoehnlein** [comment]
Sounds good.

**Comment by spoenemann** [comment]
Most parts have been solved with #202.

_It should be possible to remove control points from an edge_ &rarr; #206.
