### ISSUE TITLE
[npm] missing dependencies

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/sprotty#140]
Seems like the setup of the Jenkins build introduced new dependencies which are not listed in package.json. As a result, I can no longer run the tests locally.

Missing packages are
* jenkins-mocha
* tsc-watch

Also, the test coverage script config has gone.

**Comment by spoenemann** [comment]
I think this is not due to missing dependencies, but rather about running the locally installed executables instead of relying on the globally installed ones. We should fix the scripts in package.json.

**Comment by JanKoehnlein** [comment]
Seems to have been an invalid intermediate state on my side.

Also checked that `npm` prepends `./node_modules/.bin` on the PATH when runnign scripts, such that binaries from the global config are shadowed.
