### ISSUE TITLE
Add SVG export

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/sprotty#145]
Make it possible to export the diagram in SVG format.

**Comment by JanKoehnlein** [comment]
https://github.com/theia-ide/sprotty/pull/146/files

Some issues remain
- [ ] styles from less files included from bootstrap are not inspectable
- [ ] currently all stylesheets are merged into the SVG. We should restrict that to the needed ones
- [ ] pre-rendered shapes are dislocated on export

**Comment by JanKoehnlein** [comment]
styles from less files included from bootstrap are not inspectable:
This is not related to less, but to the fact that the css is fetched from a different site. Chrome disallows the inspection of such files. We should issue a warning about missing styles.

**Comment by JanKoehnlein** [comment]
- [ ] currently all stylesheets are merged into the SVG. We should restrict that to the needed ones:

This is especially bad for the Xtext examples, which include huge CSS files that are not needed.
There is no good API to inspect which CSS rules have been applied to a given DOM element. The best I could find is [this](https://stackoverflow.com/a/22638396/6176337). A solution based on this would have high complexity (#rules times #elements) which doesn't sound very appealing.

Another solution could be based on `getComputedStyles` and inlining the result as style attributes on individual SVG elements. Once again, it doesn't seem to be (easily) possible to distinguish the computed styles from the default ones. Best algorithm here seems to be to create a new iframe add an element of the given type, read its properties using `getComputedStyles` and compare these against the styles form the original element. Not so appealing either.

I'd go for a filtering approach: The implementor can programmatically filter which css files are exported.

**Comment by JanKoehnlein** [comment]
- [ ] pre-rendered shapes are dislocated on export

The bounding box of these shapes does not start at (0,0) so I had to adjust that first. This resulted in the `Alignable` interface. As a nice side effect, this will fix issues with layouting labels, as the vbox layout no longer has to take care about styles like `dominant-baseline`.

**Comment by JanKoehnlein** [comment]
https://github.com/theia-ide/sprotty/pull/147

**Comment by uruuru** [comment]
On Windows (both Chrome and Firefox) `CTRL-e` results in two diagrams being exported. 

```
11:10:14 sprotty CommandStack: Executing ExportSvgCommand {}
[...]
11:10:14 sprotty CommandStack: Executing ExportSvgCommand {}
```

**Comment by JanKoehnlein** [comment]
@uruuru covered in separate issue #150
