### ISSUE TITLE
Navigation collides with mouse gestures

### ISSUE THREAD

**Issue by le-cds** [theia-ide/sprotty#154]
Sprotty, at least by default, uses the right mouse button to move the viewport. In some browsers, this collides with mouse gestures. Also, do context menus work?

**Comment by JanKoehnlein** [comment]
Could you elaborate in which browsers you observed that and on which platforms, and which gestures?

Currently there are no context menus in sprotty. The right-click should be consumed by the mouse tool and as such not be forwarded to the application. What kind of behavior do you expect?

**Comment by le-cds** [comment]
> Could you elaborate in which browsers you observed that and on which platforms

Opera provides mouse gestures by default. On Firefox, I have the _Mouse Gestures Suite_ add-on installed. This should be independent of the platform. I'm running Mac OS X as I'm typing this.

> and which gestures?

The "Back" gesture, for example. The gesture usually is "Press right mouse button, move mouse left, release right mouse button." If I do that to move the diagram, what happens is that the browser instead navigates to the previous page. For example, go to [ELK Live](http://rtsys.informatik.uni-kiel.de/elklive/), click on the "ELKT Editor" button, and move the diagram the way I just described. You'll be taken back to the ELK Live homepage if you have mouse gestures installed.

> What kind of behavior do you expect?

As a user, it actually confused me that nothing happens. For example, ELK Live doesn't provide a custom context menu, so the standard browser context menu is what I would have expected.

**Comment by JanKoehnlein** [comment]
> Opera provides mouse gestures by default. On Firefox, I have the Mouse Gestures Suite add-on installed. This should be independent of the platform. I'm running Mac OS X as I'm typing this.

Interesting. How do these behave with e.g. Google Maps, where a right-click drag results in a zoom?

If we bound panning to left-click drag by default, would that collide with something else?

**Comment by le-cds** [comment]
> Interesting. How do these behave with e.g. Google Maps, where a right-click drag results in a zoom?

The mouse gesture wins. In fact, I didn't even know that right-click-drag zooms since simple using the mouse wheel also zooms.

> If we bound panning to left-click drag by default, would that collide with something else?

No, that would be fine. In fact, it would probably be a better match for user expectations since that's how panning works in Google Maps and similar applications. I was wondering why that wasn't already the default. My best guess was that you wanted to reserve left-click-drag for selections.

**Comment by spoenemann** [comment]
Maybe we could offer two interaction modes:

 1. *Viewer* (Google Maps style, default setting): pan with left-click-drag
 2. *Editor*: pan with right-click-drag, select multiple items with left-click-drag

**Comment by uruuru** [comment]
> Google Maps, where a right-click drag results in a zoom?

Out of curiosity: We were not able to see this behavior, neither on Windows, nor on Linux, or Mac (Firefox, Chrome, Safari).

**Comment by spoenemann** [comment]
Another reason for making left-click-drag the preferred scroll tool: right-click-drag [does not work in the SWT browser](https://bugs.eclipse.org/bugs/show_bug.cgi?id=211224).

**Comment by JanKoehnlein** [comment]
Switched to left-drag for panning.
