### ISSUE TITLE
Harmonize APIs

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/sprotty#167]
- [x] IDiagramServer on client and server
- [x] SelectAction and CollapseExpandAction

**Comment by spoenemann** [comment]
- [ ] Move model elements that have a more general scope than graphs from `graph.ts` to the local `model.ts` of the corresponding features.

**Comment by JanKoehnlein** [comment]
I don't remember what IDiagramServer on client and server was about. closing
