### ISSUE TITLE
is there a simple example of implementing a WebSocketDiagramServer?

### ISSUE THREAD

**Issue by ryaneberly** [theia-ide/sprotty#184]
There are some great examples in this repo.  But the server side examples seems to all be integrated with an xtext editor.   It would be helpful to me to understand what a vanilla server side model would look like without the other extras.

**Comment by spoenemann** [comment]
There has been a very simple example that we removed some time ago. You can still find it here:

https://github.com/theia-ide/sprotty/tree/v0.1.2/server/diagram-server-examples

**Comment by ryaneberly** [comment]
@spoenemann ,  thank you.  That's helpful.
