### ISSUE TITLE
Problems with `org.eclipse.xtend.lib.annotations.Accessors` xtend-gen Java Classes

### ISSUE THREAD

**Issue by MattsSe** [theia-ide/sprotty#186]
I added sprotty as a submodule to my personal project to play around a bit and I noticed some odd behavior with the `@Accessors` annotations, especially in the `io.typefox.sprotty.server.xtext.LanguageAwareDiagramServer` class.

It seems that the getter and setter for `languageServerExtension` are not generated in the Java class.

In LanguageAwareDiagramServer.xtend:
`@Accessors
DiagramLanguageServerExtension languageServerExtension`

In the generated LanguageAwareDiagramServer.java are no getter/setter present:
`/* @Accessors
*/private DiagramLanguageServerExtension languageServerExtension;`

I get the following Error in the xtend class (I'm using Intellij):
```
Error:(27, 2) Error during annotation processing:
java.lang.NoSuchMethodError: org.eclipse.xtext.xbase.lib.CollectionLiterals.newArrayList()Ljava/util/ArrayList;
	at org.eclipse.xtend.lib.annotations.FinalFieldsConstructorProcessor$Util.getFinalFieldsConstructorArgumentTypes(FinalFieldsConstructorProcessor.java:99)
	at org.eclipse.xtend.lib.annotations.FinalFieldsConstructorProcessor$Util.hasFinalFieldsConstructor(FinalFieldsConstructorProcessor.java:77)
	at org.eclipse.xtend.lib.annotations.FinalFieldsConstructorProcessor$Util.needsFinalFieldConstructor(FinalFieldsConstructorProcessor.java:71)
	at org.eclipse.xtend.lib.annotations.DataProcessor.doTransform(DataProcessor.java:82)
	at org.eclipse.xtend.lib.macro.AbstractClassProcessor.doTransform(AbstractClassProcessor.java:42)
```

However `gradle build` finishes successfully and I can run the project without problems with `gradle jettyRun`. But If I want to run a class from inside my project, which depends on the `xtend-diagram` module, It won't compile.

**Comment by JanKoehnlein** [comment]
Xtend support in IDEA is outdated and deprecated. It is likely you run into such problems. 
If you want/have to use IDEA, I'd recommend to use Java and consume the sprotty/server projects from sonatype snapshots. See e.g. the yang-lsp project for an example:
https://github.com/theia-ide/yang-lsp/blob/master/yang-lsp/build.gradle (repo config)
https://github.com/theia-ide/yang-lsp/blob/master/yang-lsp/io.typefox.yang.diagram/build.gradle (dependencies)

**Comment by MattsSe** [comment]
Thanks for your quick response. I'll give it a try.
Closing this.

**Comment by JanKoehnlein** [comment]
While my initial command still holds, this looks like the `org.eclipse.xtext.xbase.lib` is missing on the classpath. Or wrong version as there have been some changes to this part of the runtime lib in Xtext 2.13.

**Comment by cdietrich** [comment]
see https://www.eclipse.org/forums/index.php/t/1088834/
