### ISSUE TITLE
Build failed with exception can't find InternalMulticoreAllocationLexer.java.

### ISSUE THREAD

**Issue by Benson666** [theia-ide/sprotty#192]
When I exe 'gradlew.bat jettyRun', the building process exit with an exception:

Caused by: java.io.FileNotFoundException: F:\download\sprotty-master\server\xtext-di
agram-examples\io.typefox.sprotty.example.multicore\..\io.typefox.sprotty.exampl
e.multicore\src\main\xtext-gen\io\typefox\sprotty\example\multicore\parser\antlr
\internal\InternalMulticoreAllocationLexer.java (system cannot find the specified file.)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:125)
        at com.google.common.io.Files$FileByteSource.read(Files.java:140)
        at com.google.common.io.Files.toByteArray(Files.java:250)
        at org.eclipse.xtext.generator.JavaIoFileSystemAccess.readTextFile(JavaI
oFileSystemAccess.java:253)
        ... 18 more

        at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.handleIssues(Mwe2Bridge.java:
56)
        at org.eclipse.emf.mwe.core.lib.Mwe2Bridge.invoke(Mwe2Bridge.java:48)
        at org.eclipse.emf.mwe.core.lib.AbstractWorkflowComponent.invoke(Abstrac
tWorkflowComponent.java:201)
        at org.eclipse.emf.mwe2.runtime.workflow.AbstractCompositeWorkflowCompon
ent.invoke(AbstractCompositeWorkflowComponent.java:35)
        at org.eclipse.emf.mwe2.runtime.workflow.Workflow.run(Workflow.java:19)
        at org.eclipse.emf.mwe2.launch.runtime.Mwe2Runner.run(Mwe2Runner.java:10
2)
        ... 4 more
:xtext-diagram-examples:io.typefox.sprotty.example.multicore:generateXtextLangua
ge FAILED
------------------------------------------------------------------------------------
Where can I get this file or skip the problem?

**Comment by JanKoehnlein** [comment]
Looks like some prior step went wrong during the execution of the workflow, as it is responsible for generating this file. Could you try `gradlew -d` to see if some error got swallowed?

Other than that, there seems to be a `\` missing in the file path before the `..` which is strange as it doesn't happen on my machine.

**Comment by Benson666** [comment]
to JanKoehnlein:
    Have you builded this project in windows 7 and JDK 1.8?
    Today,I rebuild it in another pc, and I encountered another problem:

ERROR:The method getDeclarations() from the type Program refers to the missing t
ype Object (file:/F:/workspace/sprotty/server/xtext-diagram-examples/io.typefox.
sprotty.example.multicore.web/src/main/java/io/typefox/sprotty/example/multicore
/web/selection/SelectionService.xtend line : 42 column : 27)
ERROR:The method getDeclarations() from the type Program refers to the missing t
ype Object (file:/F:/workspace/sprotty/server/xtext-diagram-examples/io.typefox.
sprotty.example.multicore.web/src/main/java/io/typefox/sprotty/example/multicore
/web/selection/SelectionService.xtend line : 59 column : 27)
ERROR:The method getAllocations() from the type Step refers to the missing type
Object (file:/F:/workspace/sprotty/server/xtext-diagram-examples/io.typefox.spro
tty.example.multicore.web/src/main/java/io/typefox/sprotty/example/multicore/web
/selection/SelectionService.xtend line : 102 column : 37)
ERROR:The method getAllocations() from the type Step refers to the missing type
Object (file:/F:/workspace/sprotty/server/xtext-diagram-examples/io.typefox.spro
tty.example.multicore.web/src/main/java/io/typefox/sprotty/example/multicore/web
/selection/SelectionService.xtend line : 116 column : 37)
ERROR:The method getDeclarations() from the type Program refers to the missing t
ype Object (file:/F:/workspace/sprotty/server/xtext-diagram-examples/io.typefox.
sprotty.example.multicore.web/src/main/java/io/typefox/sprotty/example/multicore
/web/selection/SelectionService.xtend line : 121 column : 26)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xtext-diagram-examples:io.typefox.sprotty.example.mu
lticore.web:generateXtext'.
> Xtext validation failed, see build log for details.

**Comment by Benson666** [comment]
> Looks like some prior step went wrong during the execution of the workflow, as it is responsible for generating this file. Could you try gradlew -d to see if some error got swallowed?

Other than that, there seems to be a \ missing in the file path before the .. which is strange as it doesn't happen on my machine.

I have solved the problem. I can't build with master version,but it's ok with release 0.2.1.

**Comment by JanKoehnlein** [comment]
I tried again on `master` Windows 10 with a JDK 1.8 and the build went through without problems. I don't have access to a Win7 machine, but seriously doubt this is the issue.

It could be your m2 cache is corrupted because you fetched a corrupted version of Xtext. Try `gradlew -d --refresh-dependencies` to re-fetch snapshot deps.
Other than that there is little I can do without a complete log.

**Comment by spoenemann** [comment]
> I have solved the problem.

Please reopen if you still have any issues that we should look at.
