### ISSUE TITLE
Can sprotty work like GMF or Sirius？

### ISSUE THREAD

**Issue by Benson666** [theia-ide/sprotty#193]
I want to develop an IDE based on web like eclipse GMF or sirius，which can resovle ecore model 
described by XMI, then we defined every element's shape in meta model. After all we could get an 
Domain Specified Modeling Tool。I can build model with it，and export the model with XMI。 In the
 background，we drive the model transform to some text... ...
        I don't known sprotty have these abilities or not.Can you give me some advices?

**Comment by JanKoehnlein** [comment]
If it's about graphical editing, sprotty does not yet allow this. It is currently restricted to viewing graphical models. Obeo (the company behind Sirius) is currently looking into extending sprotty with editing capabilities. Maybe they are also adding some model-driven frontend to describe the editors.

In its current state, you could use sprotty to build a textual modelling tool (based on Xtext) with graphical views on top, as we do e.g. in the (Yangster)[http://typefox.io/extending-a-language-server-with-sprotty-diagrams] tool.

**Comment by spoenemann** [comment]
See https://blog.obeo.fr/modeling-tools-go-up-to-the-cloud for directions on integrating Sirius with sprotty.
