### ISSUE TITLE
Unclear how to use sprotty as node dependency

### ISSUE THREAD

**Issue by bjorncole** [theia-ide/sprotty#227]
Good morning - 

I have been experimenting with Sprotty as a take-off point for some model-based illustrations and examples for a few days. I started by making a copy of the Class diagram example and modifying it, modifying the import from paths to my file system. Using this approach, yarn builds and Webpack continue to work and incorporate modifications I make.

As soon as I try to transition to using Sprotty as a node module (adding to dependencies in package.json and redoing yarn), I cannot. The import from "sprotty" cannot find the module. Should I import under a different name? Is there a specific configuration setting needed to make it visible? Other imports like Inversify appear to be working correctly in my setup.

**Comment by JanKoehnlein** [comment]
A few things to check:
- Maybe your install went wrong Is `node_modules/sprotty` populated?
- Which version of sprotty did you import?
- The `examples` folder is not published with the npm package. Maybe you're still referring to classes in there?
- `sprotty` provides a big `lib/index.ts` file. When consuming sprotty from npm, imports should look like this:
```js
import {
    RenderingContext,
    SEdge,
    SCompartment,
    PolylineEdgeView,
    Point,
    toDegrees, IView, setAttr
} from "sprotty/lib"
``` 

If that doesn't help, could you share some code to reproduce it?

**Comment by bjorncole** [comment]
Aha. It was the "sprotty/lib" that did the trick. I was simply using "sprotty" rather than "sprotty/lib."
