### ISSUE TITLE
[flow] Center nodes horizontally in auto-layout

### ISSUE THREAD

**Issue by JanKoehnlein** [theia-ide/sprotty#77]
Looks a bit strange currently, especially on the left-hand side of the attached diagram

<img width="481" alt="screen shot 2017-05-02 at 15 06 21" src="https://cloud.githubusercontent.com/assets/377752/25618898/18488ff4-2f49-11e7-9e88-1a4078242633.png">

**Comment by spoenemann** [comment]
We cannot solve this in sprotty. If this is still relevant, a new issue should be opened for [ELK](https://github.com/eclipse/elk/issues).
